language: cpp

dist: precise
sudo: false

addons:
  apt:
    packages:
      - intltool
      - autoconf
      - autopoint
      - libxml2-dev
      - pciutils-dev
      - libgtk2.0-dev

install:
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/
  - git clone https://github.com/ddccontrol/ddccontrol.git ${TRAVIS_BUILD_DIR}/deps/ddccontrol
  - bash -c "cd ${TRAVIS_BUILD_DIR}/deps/ddccontrol && ./autogen.sh && ./configure && make -j4"
  - export PATH="${TRAVIS_BUILD_DIR}/deps/ddccontrol/src/ddccontrol:${PATH}"

script:
  - ./autogen.sh
  - ./configure
  - make -j4
  - make check-db
  - '[ "$(git status -s)" == "" ] && echo "GOOD: git files are unchanged after build"'

